In [2]:
import torch
import torch.nn as nn

torch.manual_seed(1)

In [3]:
class Softmax(nn.Module):
    def __init__(self, in_size, out_size):
        super(Softmax, self).__init__()
        self.linear = nn.Linear(in_size, out_size)

    def forward(self, x):
        yhat = self.linear(x)
        return yhat

model = Softmax(2, 3)

In [17]:
x = torch.tensor([[1.0, 2.0]])
z = model(x)
print(z)
print(z.argmax())

tensor([[-0.4053,  0.8864,  0.2807]], grad_fn=<AddmmBackward>)
tensor(1)


In [18]:
_, yhat = z.max(1)
print(yhat)

tensor([1])


In [19]:
x = torch.tensor(([1.0, 1.0], [1.0, 2.0], [1.0, 3.0]))
z = model(x)
print(z)

tensor([[-0.0932,  0.5545, -0.1433],
        [-0.4053,  0.8864,  0.2807],
        [-0.7174,  1.2183,  0.7048]], grad_fn=<AddmmBackward>)


In [20]:
_, yhat = z.max(1)
print(yhat)

tensor([1, 1, 1])
