In [1]:
import torch
import torch.nn as nn

In [2]:
torch.manual_seed(1)

In [3]:
model = nn.Linear(in_features=2, out_features=1)

In [4]:
list(model.parameters())

[Parameter containing:
 tensor([[ 0.3643, -0.3121]], requires_grad=True),
 Parameter containing:
 tensor([-0.1371], requires_grad=True)]

In [5]:
model.state_dict()

OrderedDict([('weight', tensor([[ 0.3643, -0.3121]])),
             ('bias', tensor([-0.1371]))])

In [6]:
x = torch.tensor([1.0, 3.0])
yhat = model(x)
yhat

tensor([-0.7090], grad_fn=<AddBackward0>)

In [8]:
x = torch.tensor([[1.0, 1.0], [1.0, 2.0], [1.0, 3.0]])
yhat = model(x)
yhat

tensor([[-0.0848],
        [-0.3969],
        [-0.7090]], grad_fn=<AddmmBackward>)

In [11]:
class linear_regression(nn.Module):
    def __init__(self, input_size, output_size):
        super(linear_regression, self).__init__()
        self.linear = nn.Linear(input_size, output_size)

    def forward(self, x):
        yhat = self.linear(x)
        return yhat

In [12]:
model = linear_regression(input_size=2, output_size=1)

In [13]:
yhat = model(x)
yhat

tensor([[ 0.0903],
        [-0.5754],
        [-1.2411]], grad_fn=<AddmmBackward>)