In [2]:
### 2D tensor ###
import torch

In [3]:
a = [[11, 12, 13], [21, 22, 23], [31, 32, 33]]
A = torch.tensor(a)
A

tensor([[11, 12, 13],
        [21, 22, 23],
        [31, 32, 33]])

In [4]:
A.ndimension()

2

In [5]:
A.shape

torch.Size([3, 3])

In [6]:
A.size()

torch.Size([3, 3])

In [7]:
A.numel()

9

In [8]:
### indexing and slicing in 2D ###
A[1][2]

tensor(23)

In [10]:
A[0][2]

tensor(13)

In [11]:
A[0, 0:2]

tensor([11, 12])

In [12]:
A[1:3, 2]

tensor([23, 33])

In [13]:
## basic operations in 2D ###

x = torch.tensor([[1,0], [0,1]])
y = torch.tensor([[2,1], [1,2]])
z = x + y
z

tensor([[3, 1],
        [1, 3]])

In [14]:
y = torch.tensor([[2,1], [1,2]])
z = 2 * y
z

tensor([[4, 2],
        [2, 4]])

In [15]:
x = torch.tensor([[1,0], [0,1]])
y = torch.tensor([[2,1], [1,2]])
z = x * y
z

tensor([[2, 0],
        [0, 2]])

In [18]:
x = torch.tensor([[0,1,1], [1,0,1]])
y = torch.tensor([[1,1], [1,1], [-1,1]])
z = torch.mm(x,y)
z

tensor([[0, 2],
        [0, 2]])