In [1]:
### 1D tensor ###
import torch

In [2]:
a = torch.tensor([7, 4, 3, 2, 6])

In [3]:
a[0]

tensor(7)

In [4]:
a.dtype

torch.int64

In [5]:
a = torch.tensor([0.0, 1.0, 2.0, 3.0, 4.0])
a.dtype

torch.float32

In [10]:
a = torch.tensor([0.0, 1.0, 2.0, 3.0, 4.0], dtype=torch.int32)
a.dtype

<ipython-input-10-142c37d6ade7>:1: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  a = torch.tensor([0.0, 1.0, 2.0, 3.0, 4.0], dtype=torch.int32)


torch.int32

In [11]:
a = torch.FloatTensor([0, 1, 2, 3, 4])
a.dtype

torch.float32

In [12]:
a

tensor([0., 1., 2., 3., 4.])

In [13]:
a = torch.tensor([0, 1, 2, 3, 4])
a = a.type(torch.FloatTensor)
a.dtype

torch.float32

In [14]:
a.size()

torch.Size([5])

In [15]:
a.ndimension()

1

In [16]:
a_col = a.view(5, 1)

In [17]:
a_col = a.view(-1, 1)

In [18]:
a = torch.tensor([0, 1, 2, 4, 5, 5, 6])
a_col = a.view(7, 1)
a_col

tensor([[0],
        [1],
        [2],
        [4],
        [5],
        [5],
        [6]])

In [19]:
a_col = a.view(-1, 1)
a_col

tensor([[0],
        [1],
        [2],
        [4],
        [5],
        [5],
        [6]])

In [21]:
import numpy as np
np_array = np.array([0.0, 1.0, 2.0, 3.0, 4.0])
torch_tensor = torch.from_numpy(np_array)
torch_tensor.dtype

torch.float64

In [25]:
back_to_np = torch_tensor.numpy()
back_to_np

array([0., 1., 2., 3., 4.])

In [24]:
import pandas as pd
pd_series = pd.Series([0.1, 2.0, 0.3, 10.1])
pd_series

0     0.1
1     2.0
2     0.3
3    10.1
dtype: float64

In [27]:
pd_series.values

array([ 0.1,  2. ,  0.3, 10.1])

In [28]:
pd_to_torch = torch.from_numpy(pd_series.values)
pd_to_torch.dtype

torch.float64

In [29]:
a = torch.tensor([0, 1, 2, 3])
torch_to_list = a.tolist()
torch_to_list

[0, 1, 2, 3]

In [33]:
a = torch.tensor([5, 2, 6, 1])

a0 = a[0]
a1 = a[1]
print(a0)
print(a1)

print(a[0].item())
print(a[1].item())

tensor(5)
tensor(2)
5
2


In [34]:
### slice ###
a = torch.tensor([20, 1, 2, 3, 4])
a

tensor([20,  1,  2,  3,  4])

In [35]:
a[0] = 100
a

tensor([100,   1,   2,   3,   4])

In [37]:
print(a[0:4])
print(a[1:5])

tensor([100,   1,   2,   3])
tensor([1, 2, 3, 4])


In [41]:
a[1:3] = torch.tensor([300.0, 400.0])
a

tensor([100, 300, 400,   3,   4])

In [43]:
### basic operations ###
u = torch.tensor([1.0, 0.0])
v = torch.tensor([0.0, 1.0])
z = u + v
z

tensor([1., 1.])

In [44]:
y = torch.tensor([1, 2])
z = y * 2
z

tensor([2, 4])

In [45]:
u = torch.tensor([1, 2])
v = torch.tensor([3, 2])
z = u * v
z

tensor([3, 4])

In [46]:
u = torch.tensor([1, 2])
v = torch.tensor([3, 1])
dot = torch.dot(u, v)
dot

tensor(5)

In [47]:
u = torch.tensor([1, 2, 3, -1])
z = u + 1
z

tensor([2, 3, 4, 0])

In [51]:
### functions ###
a = torch.tensor([1.0, 1.0, 1.0, 1.0])
a.mean()

tensor(1.)

In [52]:
a = torch.tensor([1, 2, 3, 4])
a.max()

tensor(4)