In [1]:
import torch

In [2]:
a = torch.tensor([7, 4, 3, 2, 6])

In [3]:
a[0]

tensor(7)

In [4]:
a.dtype

torch.int64

In [5]:
a = torch.tensor([0.0, 1.0, 2.0, 3.0, 4.0])
a.dtype

torch.float32

In [10]:
a = torch.tensor([0.0, 1.0, 2.0, 3.0, 4.0], dtype=torch.int32)
a.dtype

<ipython-input-10-142c37d6ade7>:1: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  a = torch.tensor([0.0, 1.0, 2.0, 3.0, 4.0], dtype=torch.int32)


torch.int32

In [11]:
a = torch.FloatTensor([0, 1, 2, 3, 4])
a.dtype

torch.float32

In [12]:
a

tensor([0., 1., 2., 3., 4.])

In [13]:
a = torch.tensor([0, 1, 2, 3, 4])
a = a.type(torch.FloatTensor)
a.dtype

torch.float32

In [14]:
a.size()

torch.Size([5])

In [15]:
a.ndimension()

1

In [16]:
a_col = a.view(5, 1)

In [17]:
a_col = a.view(-1, 1)

In [18]:
a = torch.tensor([0, 1, 2, 4, 5, 5, 6])
a_col = a.view(7, 1)
a_col

tensor([[0],
        [1],
        [2],
        [4],
        [5],
        [5],
        [6]])

In [19]:
a_col = a.view(-1, 1)
a_col

tensor([[0],
        [1],
        [2],
        [4],
        [5],
        [5],
        [6]])