In [1]:
### liner regression ###
import torch

In [3]:
w = torch.tensor(2.0, requires_grad=True)
b = torch.tensor(-1.0, requires_grad=True)

def forward(x):
    y = w*x + b
    return y

x = torch.tensor([1.0])
yhat = forward(x)
yhat

tensor([1.], grad_fn=<AddBackward0>)

In [5]:
x = torch.tensor([[1], [2]])
yhat = forward(x)
yhat

tensor([[1.],
        [3.]], grad_fn=<AddBackward0>)

In [7]:
### class linear ###
import torch.nn as nn
torch.manual_seed(1)
model = nn.Linear(in_features=1, out_features=1)
print(list(model.parameters()))

[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]


In [8]:
x = torch.tensor(([0.0]))
yhat = model(x)
yhat

tensor([-0.4414], grad_fn=<AddBackward0>)

In [9]:
x = torch.tensor(([[1.0], [2.0]]))
yhat = model(x)
yhat

tensor([[0.0739],
        [0.5891]], grad_fn=<AddmmBackward>)

In [11]:
### custom modules ###
class LR(nn.Module):
    def __init__(self, in_size, output_size):
        super(LR, self).__init__()
        self.linear = nn.Linear(in_size, output_size)

    def forward(self, x):
        out = self.linear(x)
        return out

In [12]:
model = LR(1, 1)

model.state_dict()["linear.weight"].data[0] = torch.tensor([0.5153])
model.state_dict()["linear.bias"].data[0] = torch.tensor([-0.4414])

print(list(model.parameters()))

[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]


In [14]:
x = torch.tensor([1.0])
yhat = model(x)
yhat

tensor([0.0739], grad_fn=<AddBackward0>)

In [15]:
x = torch.tensor(([[1.0], [2.0]]))
yhat = model(x)
yhat

tensor([[0.0739],
        [0.5892]], grad_fn=<AddmmBackward>)

In [17]:
print(model.state_dict())
print(model.state_dict().keys())
print(model.state_dict().values())

OrderedDict([('linear.weight', tensor([[0.5153]])), ('linear.bias', tensor([-0.4414]))])
odict_keys(['linear.weight', 'linear.bias'])
odict_values([tensor([[0.5153]]), tensor([-0.4414])])
